apiVersion: apps/v1
kind: Deployment
metadata:
  name: watch-image
  namespace: default
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      run: watch-image
  template:
    metadata:
      labels:
        run: watch-image
    spec:
      containers:
      - image: docker.io/andres112/watch-image:latest
        imagePullPolicy: Always
        name: watch-image
        ports:
        - containerPort: 1080
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: watch-info
  namespace: default
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      run: watch-info
  template:
    metadata:
      labels:
        run: watch-info
    spec:
      containers:
      - image: docker.io/andres112/watch-info:latest
        imagePullPolicy: Always
        name: watch-info
        ports:
        - containerPort: 1080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: watch-image
  namespace: default
spec:  
  ports:
    - port: 1080
      protocol: TCP
      targetPort: 1080
  selector:
    run: watch-image
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: watch-info
  namespace: default
spec:  
  ports:
    - port: 1080
      protocol: TCP
      targetPort: 1080
  selector:
    run: watch-info
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: watch-ingress
  namespace: default
spec:
  rules:
  - http:
      paths:
      - path: /image/v1/*
        backend:
          serviceName: watch-image
          servicePort: 1080
      - path: /info/v1/*
        backend:
          serviceName: watch-info
          servicePort: 1080