apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: watches-image
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: watches-image
  template:
    metadata:
      labels:
        run: watches-image
    spec:
      containers:
      - image: docker.io/andres112/watches-image:latest
        imagePullPolicy: IfNotPresent
        name: watches-image
        ports:
        - containerPort: 1080
          protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: watches-info
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: watches-info
  template:
    metadata:
      labels:
        run: watches-info
    spec:
      containers:
      - image: docker.io/andres112/watches-info:latest
        imagePullPolicy: IfNotPresent
        name: watches-info
        ports:
        - containerPort: 1080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: watches-image
  namespace: default
spec:  
  ports:
    - port: 1080
      protocol: TCP
      targetPort: 1080
  selector:
    run: watches-image
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: watches-info
  namespace: default
spec:  
  ports:
    - port: 1080
      protocol: TCP
      targetPort: 1080
  selector:
    run: watches-info
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: watches-ingress
  namespace: default
spec:
  rules:
  - http:
      paths:
      - path: /image/v1/*
        backend:
          serviceName: watches-image
          servicePort: 1080
      - path: /info/v1/*
        backend:
          serviceName: watches-info
          servicePort: 1080