version: '3'

services:
  db:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: watches
      MYSQL_USER: watches
      MYSQL_PASSWORD: watches
      MYSQL_DATABASE: watches
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment: 
      -PMA_HOST: db
    ports:
      - "2080:80"
  watches:
    build: .
    depends_on:
      - db
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DBNAME: watches
      DB_USER: watches
      DB_PASS: watches
      HTTP_USER: cloud
      HTTP_PASS: computing
    ports:
      - "1080:1080"